### PR TITLE
added navigation to the home page after login, also corrected courseM…

### PR DESCRIPTION
**Pull request by AndrewAlien**
…anagement to display TAs and their assignments, implemented createCourse function

### CODE REVIEW

**Review by Kretsch-Matt — APPROVED** [review]

**Comment by AndrewAlien** [comment]
i made another commit to refactor my mess and add in a message for when the course was created or failed to do so on top of the previous changes

**Comment by Kretsch-Matt** [comment]
> i made another commit to refactor my mess and add in a message for when the course was created or failed to do so on top of the previous changes

are you trying to pull a fast one after I approved the initial commit

**Comment by AndrewAlien** [comment]
> > i made another commit to refactor my mess and add in a message for when the course was created or failed to do so on top of the previous changes
> 
> are you trying to pull a fast one after I approved the initial commit
>
lol i didnt think about what i was doing till after i pushed that's why i confessed my sneak tactics

**Review by Rorr4 — APPROVED** [review]
I'll approve this!

**Pull request merged**
